import paho.mqtt.client as mqtt
import os
import re
import sys
import time
import threading
import random
from collections import defaultdict

# Aktuellen Dateipfad holen, dann ein Verzeichnis nach oben (../code)
base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(base_dir)

import messageClient.mqtt_broker_listener as broker_listener

global MQTT_Publish_Topic, MQTT_Result_Topic, MQTT_Username, MQTT_Password

client = None
client_id = "TaskManager"
MQTT_Port = 1883
MQTT_Username = "user1"
MQTT_Password = "WhHe1NPfDBJ%"
MQTT_Publish_Topic = "mqttTester"
MQTT_Result_Topic = "mqttTester/results"
MQTT_Task_Generator_Topic = "task_generator"
connected_clients = set()  # unique set of connected PCs
ping_event = threading.Event()  # event to control ping threads
stop_event = threading.Event()
task_event = threading.Event()
message_count = 0  # counter for received messages on results topic
task_count = 0  # counter for loaded tasks
# "Zeitstempel_Aufgabenanzahl_TM.txt"
timestamp_file = None
log_lock = threading.Lock() # ensure logging 
iteration = 0

# global task list
task_list = []
task_lock = threading.Lock()  # ensure thread-safe access to task_list

# Nicole: MQTT-Verbindung vorbereiten
# mqtt_broker = "192.168.178.63" # TOODO: Broker nicht hard coden
# mqtt_client = mqtt.Client(client_id="Task_Manager")  # Nicole: Kein callback_api_version für paho-mqtt < 2.0
# mqtt_client.connect(mqtt_broker)

# Nicole: Task_mode aus Dateinamen extrahieren
script_name = os.path.basename(__file__)
task_mode = script_name.split("_")[1] if "_" in script_name else "unknown"
print(f"# Nicole: Extrahierter Task_mode: {task_mode}")

# Add the parent directory (where "taskGenerator" is) to the Python path
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

# get the latest broker ip of the broker which was started
def get_broker_ip_via_file():
   broker_dir = os.path.join(parent_dir, "messageBroker")
   ip_file = os.path.join(broker_dir, "broker_ip_log.txt")

   try:
      with open(ip_file, 'r', encoding='utf-8') as file:
         broker_ip = file.read().strip()
      return broker_ip
   except FileNotFoundError:
      print(f"File {ip_file} not found")

# function to read tasks from file and populate task_list
def load_tasks_from_file(client):
   global task_list
   global task_count
   global timestamp_file
   global message_count # Nicole
   global iteration # Nicole

   generator_dir = os.path.join(parent_dir, "taskGenerator")
   manager_dir = os.path.join(parent_dir, "taskManager")

   # log dir for logs of the TM in regards of processing and distributing the tasks
   log_directory = os.path.join(manager_dir, 'logs')
   if not os.path.exists(log_directory):
      os.makedirs(log_directory)

   # change this if you use different generators!!
   task_file = os.path.join(generator_dir, "testing_tt_tasks.txt")

   task_list.clear()
   task_count = 0  # Zurücksetzen von task_count # Nicole
   message_count = 0  # Zurücksetzen von message_count # Nicole
   iteration += 1 # Nicole: Zähler für die Anzahl der Iterationen
   try:
      with open(task_file, 'r', encoding='utf-8') as file:
         with task_lock:
            print("loading tasks from file...")
            # load tasks from file that was generated by task_generator
            loaded_tasks = [line.strip() for line in file.readlines() if line.strip()]
            num_conn_clients = len(connected_clients) # Nicole  
            num_loaded_tasks = len(loaded_tasks) # Nicole
            task_count = len(loaded_tasks) * num_conn_clients # Nicole hinzugefü
            
            client.publish("infos/task_per_client", str(num_loaded_tasks), qos=1) # status=0 cause it stops to distribute tasks
            client.publish("infos/clientcount", str(num_conn_clients), qos=1) # status=0 cause it stops to distribute tasks
            client.publish("infos/taskcount", str(task_count), qos=1)
            client.publish("infos/iteration", str(iteration), qos=1)
            print(f"Published iteration: {iteration} to infos/iteration")

            # set path for timestamp_file
            timestamp = time.strftime("%Y-%m-%d %H-%M-%S")
            timestamp_file = os.path.join(log_directory, f"{timestamp}_{task_count}_TM.txt")

            # extend every task with sender and random receiver -> only for random distribution
            for client in connected_clients:
               task_list.extend(f"{task} sender={client_id}, receiver={client}\"" for task in loaded_tasks)

      print(f"Loaded tasks: {len(task_list)}")
   except Exception as e:
      print(f"File {task_file} not found Error loading tasks:{e}.")

def find_receiver(task):
   # Regulärer Ausdruck, um den receiver-Wert zu extrahieren
   match = re.search(r'receiver=([^\s,]+)', task)
   # Wenn ein Treffer gefunden wird, den receiver ausgeben
   if match:
         receiver = match.group(1).rstrip('"')
         return receiver
   else:
         print("No receiver found")

# distrbute available tasks randomly to the connected clients
def distribute_tasks(client):
    global task_list

    while not stop_event.is_set():
      if not connected_clients:
         print("No connected clients. Waiting...")
         time.sleep(5)
         continue

      with task_lock:
         if not task_list:
            print("No tasks available. Waiting for new tasks...")
            time.sleep(5)
            continue
      
         while task_list:
            task = task_list.pop(0)  # get the first task and release it from the task stack
            target_client = find_receiver(task)  # Find the receiver for this task

            # create a list to hold all tasks for the same receiver
            combined_tasks = [task]  # start with the first task

            # find all other tasks with the same receiver and add them together
            i = 0
            next_target_client = ""

            while i < len(task_list):
               next_task = task_list[i]
               next_target_client = find_receiver(next_task)

               # if the receiver matches, add the task to the combined list
               if next_target_client == target_client:
                  combined_tasks.append(next_task)
                  # remove the task from the list, so it doesn´t appear twice
                  task_list.pop(i)
               else:
                  # otherwise, move to the next task in the list
                  i += 1

            number_of_tasks = len(combined_tasks)
            log_event(f"{number_of_tasks} tasks for {target_client}")

            # combine all tasks for the receiver into one string to send them together
            task_string = "\n".join(combined_tasks)

            # check if the target client is connected and then send task to the right client
            if target_client in connected_clients:
               client.publish("start_stop/taskWorker", 1, qos=1) # status=1 cause it starts to distribute tasks
               client.publish(f"tasks/{target_client}", task_string, qos=1)
               print(f"Sent {number_of_tasks} tasks to {target_client}.")
            else:
               print(f"Target client {target_client} is not connected. Skipping.")

         time.sleep(2) # small delay to avoid overwhelming mqtt

# send pings to clients
def send_ping(client):
   while not stop_event.is_set():
      ping_event.wait()  # wait until event starts
      client.publish("ping/request", "Ping from TaskManager", qos=1)
      time.sleep(10)

# monitor active clients
def monitor_clients():
   global ping_event

   while not stop_event.is_set():
      print(f"Active clients: {connected_clients}")
      if connected_clients and not ping_event.is_set():
         print("Clients connected. Resuming ping...")
         ping_event.set()  # activate ping
      elif not connected_clients and ping_event.is_set():
         print("No clients connected. Pausing ping...")
         ping_event.clear()  # pause ping
      time.sleep(10)

# callback function for mqtt connection
def on_connect(client, userdata, flags, rc):
   print("Connected with result code " + str(rc))
   client.subscribe(MQTT_Publish_Topic, qos=0) # channel to deal with tasks
   client.subscribe(MQTT_Result_Topic, qos=0)
   client.subscribe("status/#") # subscribe to the status of all clients to monitor who is connected
   client.subscribe("ping/response/#") # listen for ping responses
   client.subscribe(MQTT_Task_Generator_Topic, qos=0) # listen to the task_generator

def log_event(event):
   global timestamp_file
   if timestamp_file is None:
      print("Error: Timestamp file path is not set. Please load tasks first.")
      return

   timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
   log_entry = f"[{timestamp}] {event}\n"
   print(log_entry, end="")

   try:
      with open(timestamp_file, "a", encoding="utf-8") as file:
         file.write(log_entry)
   except Exception as e:
      print(f"Error in logging event: {e}")

# callback when receiving messages
def on_message(client, userdata, msg):
   global task_list
   global message_count
   message = msg.payload.decode()
   topic = msg.topic

   print(f"Message received on {msg.topic}: {message}")

   # count messages on the results topic
   if topic == MQTT_Result_Topic:
      message_count += 1
      if message_count == task_count and task_count > 0:
         log_event(f"All tasks have been processed: done_tasks = {message_count}, init_tasks {task_count}")
         client.publish("start_stop/taskWorker", 0, qos=1) # status=0 when all clients worked the tasks

   # check for status messages
   if topic.startswith("status/"):
      client_name = topic.split("/")[1]
      if "Disconnected" in message:
         connected_clients.discard(client_name)
      elif "Connected" in message:
         connected_clients.add(client_name)
   # check for ping answers
   elif topic.startswith("ping/response/"):
      client_name = topic.split("/")[-1]
      connected_clients.add(client_name)

   # extract clients which introduce themselves
   elif topic.startswith("task_generator"):
      print("Task generator triggered. Loading tasks...")
      load_tasks_from_file(client)

   match = re.search(r"My name is (\w+)", message)
   if match:
      connected_pc = match.group(1)
      connected_clients.add(connected_pc)

if __name__ == '__main__':
   client = mqtt.Client(client_id="Task_Manager") # Nicole

   client.on_connect = on_connect
   client.on_message = on_message
   client.username_pw_set(username=MQTT_Username, password=MQTT_Password)

   # set Last Will Message so the manager knows where not to give tasks anymore
   client.will_set(f"status/{client_id}", "Disconnected", qos=1, retain=True)

   # Get the broker ip from the mDNS
   broker_info = broker_listener.discover_broker()
   
   if broker_info:
      MQTT_Broker, Broker_Port = broker_info
      print(f"Using broker: {MQTT_Broker}:{Broker_Port}")
   else:
      print("No MQTT broker discovered, using fallback IP.")
      MQTT_Broker = get_broker_ip_via_file() or "localhost"
      Broker_Port = 1883

   try:
      # connect to MQTT broker
      client.connect(MQTT_Broker, Broker_Port)

      # start ping, monitoring and tasks thread
      ping_thread = threading.Thread(target=send_ping, args=(client,))
      monitor_thread = threading.Thread(target=monitor_clients)
      task_thread = threading.Thread(target=distribute_tasks, args=(client,))

      ping_thread.start()
      monitor_thread.start()
      task_thread.start()

      client.loop_forever()

      # publish initial messages
      client.publish(MQTT_Publish_Topic, f"This is the Manager. My name is {client_id} and I have subscribed to topic {MQTT_Publish_Topic}.")
      client.publish(MQTT_Result_Topic, f"This is the Manager. My name is {client_id} and I have subscribed to topic {MQTT_Result_Topic}.")
      # Nicole: Zusatzinfo vor Task-Verteilung senden
      client.publish("start_stop/zusatzinfo", task_mode, retain=True)
      print(f"# Nicole: Task_mode '{task_mode}' an start_stop/zusatzinfo gesendet")


   except KeyboardInterrupt:
      print("Keyboard interrupt detected. Exiting gracefully...")

   finally:
      ping_event.set()
      stop_event.set()
      task_event.set()
      print("Set ping_event and stop_event to False.")
      client.loop_stop()
      print("Stopped client loop.")
      client.disconnect()
      print("Client disconnected.")

      # Join threads only if they are alive
      if 'ping_thread' in locals() and ping_thread.is_alive():
         ping_thread.join(timeout=5)
      if 'monitor_thread' in locals() and monitor_thread.is_alive():
         monitor_thread.join(timeout=5)
      if 'task_thread' in locals() and task_thread.is_alive():
         task_thread.join(timeout=5)

      print("Threads joined. Exiting now.")
      sys.exit(0)
