{
 "title": "40x10 Grüne Verteilung neu",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Grüne Verteilung, 50 Inferenz-Aufgaben",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"exp13\" and\r\n      r._field       == \"conn_clients\" and\r\n      r.plug         == \"Shelly1_ThinkPad\"\r\n  )\r\n  |> aggregateWindow(\r\n      every: 1m,          // 1-Minuten-Buckets\r\n      fn:     last,       // oder mean, max, min etc.\r\n      createEmpty: false  // leere Buckets weglassen\r\n    )\r\n  |> yield(name: \"conn_clients_1m\")\r\n"
    }
   ]
  },
  {
   "title": "∑ Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"energy\")\r\n  |> group()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "∑ CO₂ - E.ON Mix",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gCO₂" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"co2_grey\")\r\n  |> group()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "∑ Kosten - E.ON Mix",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"price_grey\")\r\n  |> group()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "∑ CO₂ - E.ON Öko",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gCO₂" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"co2_green\")\r\n  |> group()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "∑ Kosten - E.ON Öko",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"price_green\")\r\n  |> group()\r\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Iteration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"iteration\" and r.plug == \"Shelly1_ThinkPad\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Ø Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "energy = from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"energy\")\r\n  |> group()\r\n  |> sum(column: \"_value\")\r\n  |> rename(columns: {_value: \"total_energy\"})\r\n  |> set(key: \"join_key\", value: \"static\")\r\n\r\niteration = from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"iteration\")\r\n  |> last()\r\n  |> rename(columns: {_value: \"latest_iteration\"})\r\n  |> set(key: \"join_key\", value: \"static\")\r\n\r\njoin(\r\n  tables: {energy: energy, iteration: iteration},\r\n  on: [\"join_key\"]\r\n)\r\n|> map(fn: (r) => ({\r\n    _time: r._time,\r\n    _value: r.total_energy / float(v: r.latest_iteration)\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Ø CO₂ - E.ON Mix",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gCO₂" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "co2_grey = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"co2_grey\")\r\n    |> group()                     // alle Serien in einer Tabelle bündeln\r\n    |> sum(column: \"_value\")\r\n    |> rename(columns: {_value: \"total_co2_grey\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\niteration = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"iteration\")\r\n    |> group(columns: [])          // nur ein Wert\r\n    |> last()\r\n    |> rename(columns: {_value: \"latest_iteration\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\njoin(\r\n  tables: {co2: co2_grey, it: iteration},\r\n  on: [\"join_key\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r.latest_iteration > 0 \r\n               then r.total_co2_grey / float(v: r.latest_iteration) \r\n               else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Ø Kosten - E.ON Mix",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "price_grey = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"price_grey\")\r\n    |> group()                     // alle Serien in einer Tabelle bündeln\r\n    |> sum(column: \"_value\")\r\n    |> rename(columns: {_value: \"total_price_grey\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\niteration = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"iteration\")\r\n    |> group(columns: [])          // nur ein Wert\r\n    |> last()\r\n    |> rename(columns: {_value: \"latest_iteration\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\njoin(\r\n  tables: {cost: price_grey, it: iteration},\r\n  on: [\"join_key\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r.latest_iteration > 0 \r\n               then r.total_price_grey / float(v: r.latest_iteration) \r\n               else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Ø CO₂ - E.ON Öko",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "gCO₂" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "co2_green = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"co2_green\")\r\n    |> group()                     // alle Serien in einer Tabelle bündeln\r\n    |> sum(column: \"_value\")\r\n    |> rename(columns: {_value: \"total_co2_green\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\niteration = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"iteration\")\r\n    |> group(columns: [])          // nur ein Wert\r\n    |> last()\r\n    |> rename(columns: {_value: \"latest_iteration\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\njoin(\r\n  tables: {co2: co2_green, it: iteration},\r\n  on: [\"join_key\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r.latest_iteration > 0 \r\n               then r.total_co2_green / float(v: r.latest_iteration) \r\n               else 0.0\r\n    }))"
    }
   ]
  },
  {
   "title": "Ø Kosten - E.ON Öko",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "price_green = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"price_green\")\r\n    |> group()                     // alle Serien in einer Tabelle bündeln\r\n    |> sum(column: \"_value\")\r\n    |> rename(columns: {_value: \"total_price_green\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\niteration = \r\n  from(bucket: \"greenai_experiment18\")\r\n    |> range(start: -6h)\r\n    |> filter(fn: (r) => r._measurement == \"exp13\" and r._field == \"iteration\")\r\n    |> group(columns: [])          // nur ein Wert\r\n    |> last()\r\n    |> rename(columns: {_value: \"latest_iteration\"})\r\n    |> set(key: \"join_key\", value: \"static\")\r\n\r\njoin(\r\n  tables: {cost: price_green, it: iteration},\r\n  on: [\"join_key\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r.latest_iteration > 0 \r\n               then r.total_price_green / float(v: r.latest_iteration) \r\n               else 0.0\r\n    }))"
    }
   ]
  },
  {
   "title": "Stromverbrauch Clients",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"greenai_experiment18\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"exp13\" and r._field == \"apower\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"plug\"])"
    }
   ]
  }
 ]
}